version: "3"
services:
  python_service :
     image: my_python
     container_name: my_python_container
     build:
       context: .
       dockerfile: Dockerfile
     restart: always
     volumes:
       - /opt/logs:/opt/logs
       - /usr/app/src:/usr/app/src
